export const blockedWords = ['sex', 'fuck', 'ass', 'tits'];

export const blockedDomains = [
  'pornhub',
  'xhamster',
  'porn',
  'redtube',
  'pornstar',
  'xxx',
  'xxnx',
  'pornhat',
  '4 Porn',
  'Porn Hub XXX Videos',
  'Porn-Plus.com',
  'New Porn Video',
  'NDTube.Porn',
  'schuelerstiftung-saarburg.de',
  'SexVid',
  '18 Porn Sex',
  'Eporner',
  'Porn Biz',
  'ZBPorn',
  'PORNV.XXXX',
  'Thumbzilla',
  'HDtube.porn',
  'YouTeenPorn',
  'PornKai.com',
  'Tik.Porn',
  'qorno.com',
  'PornZog',
  'Porn TV',
  'Youjizz.com',
  'gotporn.com',
  'MAX.PORN',
  'Tubesafari.com',
  'Dino Tube',
  'SexVid XXX',
  'PornDoe',
  'Collection of Best Porn',
  'OK.PORN',
  'Tubxporn',
  'Home Porn King',
  '777.porn',
  'PornMedium.com',
  'pornhold.porn',
  'Fuck Moral',
  'AnyPorn',
  'The Porn Dude',
  'Merriam-Webster',
  'Fresh porn sex videos',
  'apornvideo.com',
  'iPornTV',
  'XXXi.PORN',
  'YouPorn',
  'Hot-Sex-Tube',
  'SpankBang',
  'PORNMATE.COM',
];
